---
driver:
  name: docker

provisioner:
  name: chef_solo
  log_level: info
  chef_license: accept

platforms:
  - name: ubuntu-16.04-chef-12
    provisioner:
      product_name: chef
      install_strategy: once
      product_version: 12
      hostname: chef-12-ubuntu.local
      run_options:
        e:
          - LANGUAGE=en_US.UTF-8
          - LC_ALL=en_US.UTF-8
  - name: ubuntu-16.04-chef-latest
    provisioner:
      product_name: chef
      install_strategy: once
      product_version: latest
      hostname: chef-latest-ubuntu.local
      run_options:
        e:
          - LANGUAGE=en_US.UTF-8
          - LC_ALL=en_US.UTF-8
  - name: centos-7.5-chef-latest
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
    provisioner:
      product_name: chef
      install_strategy: once
      product_version: latest
      hostname: chef-latest-centos.local
      run_options:
        e:
          - LANGUAGE=en_US.UTF-8
          - LC_ALL=en_US.UTF-8

suites:
  - name: default
    run_list:
      - recipe[jemalloc::default]
      - recipe[openresty::default]
      - recipe[openresty::luarocks]
    attributes:
      openresty:
        default_site_enabled: true
        link_to_jemalloc: true
        luarocks:
          default_rocks:
            luaproc: '1.0-3'
